// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
//#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using AutoManager.Application.Entities;

namespace AutoManager.Infrastructure.Models
{

    public partial class VehicleManagerContext : DbContext
    {
        public VehicleManagerContext(DbContextOptions<VehicleManagerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Car> Cars { get; set; }

        public virtual DbSet<CarStatus> CarStatuses { get; set; }

        public virtual DbSet<User> Users { get; set; }

        public virtual DbSet<Vehicle> Vehicles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Car>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__CAR__3214EC27F5EA53C6");

                entity.ToTable("CAR");

                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("ID");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("(sysdatetime())");
                entity.Property(e => e.Manufacturer)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
                entity.Property(e => e.Price).HasColumnType("decimal(12, 2)");

                entity.HasOne(d => d.Status).WithMany(p => p.Cars)
                    .HasForeignKey(d => d.StatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Car_CarStatus");
            });

            modelBuilder.Entity<CarStatus>(entity =>
            {
                entity.HasKey(e => e.Id).HasName("PK__CarStatu__3214EC07A1815E9F");

                entity.ToTable("CarStatus");

                entity.HasIndex(e => e.StatusName, "UQ__CarStatu__05E7698A53ED3A44").IsUnique();

                entity.Property(e => e.StatusName)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasIndex(e => e.Email, "IX_Users_Email").IsUnique();

                entity.Property(e => e.Id).ValueGeneratedNever();
                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(256);
                entity.Property(e => e.FullName)
                    .IsRequired()
                    .HasMaxLength(200);
                entity.Property(e => e.PasswordHash).IsRequired();
                entity.Property(e => e.Role)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            modelBuilder.Entity<Vehicle>(entity =>
            {
                entity.HasIndex(e => e.Vin, "IX_Vehicles_Vin").IsUnique();

                entity.Property(e => e.Id).ValueGeneratedNever();
                entity.Property(e => e.Make)
                    .IsRequired()
                    .HasMaxLength(100);
                entity.Property(e => e.Model)
                    .IsRequired()
                    .HasMaxLength(100);
                entity.Property(e => e.Vin)
                    .IsRequired()
                    .HasMaxLength(17);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}