// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AutoManager2.Infrastructure.EFConfig;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AutoManager2.Infrastructure.EFConfig
{
    public partial interface IVehicleManagerContextProcedures
    {
        Task<int> GenerateMockCarsAsync(int? count, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
