// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AutoManager2.Infrastructure.EFConfig;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace AutoManager2.Infrastructure.EFConfig
{
    public partial class VehicleManagerContext
    {
        private IVehicleManagerContextProcedures _procedures;

        public virtual IVehicleManagerContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new VehicleManagerContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IVehicleManagerContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class VehicleManagerContextProcedures : IVehicleManagerContextProcedures
    {
        private readonly VehicleManagerContext _context;

        public VehicleManagerContextProcedures(VehicleManagerContext context)
        {
            _context = context;
        }

        public virtual async Task<int> GenerateMockCarsAsync(int? count, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Count",
                    Value = count ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[GenerateMockCars] @Count = @Count", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
